### ISSUE TITLE
Setup a call for volunteer campaign

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#1]
- [x] Create the Google form

- [x] Get the flyer/poster created from Subani or Design team

- [x] Post announcement on Social Media

**Comment by inovizz** [comment]
Form is created already.

**Comment by kalyan678** [comment]
Announced post on social media

**Comment by inovizz** [comment]
Please announce it on mailing lists as well?

**Comment by kalyan678** [comment]
Done on HydPy mailing list. Do you want me to post it on other local groups as well?
