### ISSUE TITLE
Start CFP Counter post for Social media

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#13]
CFP Counter needs to start from today and end on 8th November.

**Comment by inovizz** [comment]
![32](https://user-images.githubusercontent.com/3849885/97662914-433a9600-1a9e-11eb-8955-e397497f5fec.png)
![33](https://user-images.githubusercontent.com/3849885/97662919-4897e080-1a9e-11eb-978d-796655fb2d4a.png)
![34](https://user-images.githubusercontent.com/3849885/97662923-4afa3a80-1a9e-11eb-8318-08be29b24df4.png)
![35](https://user-images.githubusercontent.com/3849885/97662931-4d5c9480-1a9e-11eb-8a86-4d3e60eada64.png)
![36](https://user-images.githubusercontent.com/3849885/97662935-4f265800-1a9e-11eb-9f17-e6ecb0db9c13.png)
![37](https://user-images.githubusercontent.com/3849885/97662940-50f01b80-1a9e-11eb-830e-9fbfd829a88d.png)
![38](https://user-images.githubusercontent.com/3849885/97662941-52b9df00-1a9e-11eb-8139-676699ddfedd.png)
![39](https://user-images.githubusercontent.com/3849885/97662943-53eb0c00-1a9e-11eb-95fc-e22db2e23008.png)
![40](https://user-images.githubusercontent.com/3849885/97662948-551c3900-1a9e-11eb-82ca-9d3788f5fd35.png)
![41](https://user-images.githubusercontent.com/3849885/97662949-55b4cf80-1a9e-11eb-8f81-76942fa39bcc.png)

**Comment by kalyan678** [comment]
@inovizz  Scheduled the post for 10 am tomorrow in all SMC's

**Comment by kalyan678** [comment]
@inovizz Counter posts are announced successfully. Now you can close this task.
