### ISSUE TITLE
SM - announce Community Partners

### ISSUE THREAD

**Issue by GoelJatin** [HydPy/pyconfhyd2020-tasks#19]
1. PyLadies Hyderabad
  - Logo - https://drive.google.com/file/d/0B4w3DrsBt8CjSkxGblFhOW9FaFk/view?usp=sharing
  - Website - https://pyladies.hydpy.org/
  - Twitter - pyladieshyd

2. ILUG Delhi
  - Logo - https://github.com/ILUGD/Assets/blob/master/svg/logo_ilugd.svg
  - Twitter - ilugdelhi

3. ChennaiPy
  - Logo - https://twitter.com/chennaipy/photo
  - Twitter - chennaipy

4. Co-Learning Lounge
  - Logo - 
![image](https://user-images.githubusercontent.com/14715892/98141886-27dfe880-1eed-11eb-9486-232077bb99d7.png)

  - Website - https://colearninglounge.com/
  - Twitter - ColearninLounge

5. GDG Chennai
  - Logo - https://twitter.com/GDGChennai/photo
  - Twitter - GDGChennai

More to come.. :)

**Comment by snehithallamraju** [comment]
Let me know if I can reach out to GDG Mysore for community partners. Other couple of ones I can reach out to are WiMLDS Hyd and Kaggle Days Hyd.

**Comment by inovizz** [comment]
@snehithallamraju - please do reach out to Usha for the same and also any other communities you might know.

**Comment by inovizz** [comment]
![image](https://user-images.githubusercontent.com/3849885/98460345-a082c580-21c9-11eb-965d-d76efea7b9bb.png)

**Comment by inovizz** [comment]
![6](https://user-images.githubusercontent.com/3849885/98460547-703c2680-21cb-11eb-9f3a-5fd0abf84ce0.png)
![7](https://user-images.githubusercontent.com/3849885/98460551-77633480-21cb-11eb-8518-184e17d610ef.png)
![8](https://user-images.githubusercontent.com/3849885/98460554-79c58e80-21cb-11eb-9c99-5aa6651386c9.png)
![9](https://user-images.githubusercontent.com/3849885/98460556-7af6bb80-21cb-11eb-941c-7c6f20bcb201.png)

**Comment by inovizz** [comment]
![gdg-chennai](https://user-images.githubusercontent.com/3849885/98460656-420b1680-21cc-11eb-96ea-42da3f1d0c58.png)

**Comment by inovizz** [comment]
@kalyan678 - please schedule the announcements.

**Comment by kalyan678** [comment]
@inovizz I can see two Pyladies Hyderabad posters here, but I don't see any difference between them. Should I pick anyone from them?

**Comment by inovizz** [comment]
![6](https://user-images.githubusercontent.com/3849885/99899264-efeaea80-2ccd-11eb-8ea4-d2848e5ccc66.png)
![7](https://user-images.githubusercontent.com/3849885/99899268-f5483500-2ccd-11eb-9d44-c0d7f2ef5d95.png)
![8](https://user-images.githubusercontent.com/3849885/99899269-f6796200-2ccd-11eb-8643-f9113ef38efb.png)
![9](https://user-images.githubusercontent.com/3849885/99899270-f711f880-2ccd-11eb-9538-4be09738a53c.png)
![10](https://user-images.githubusercontent.com/3849885/99899272-f7aa8f00-2ccd-11eb-8005-ab2d62948784.png)
![11](https://user-images.githubusercontent.com/3849885/99899275-f8432580-2ccd-11eb-89f3-976b9eb4cea7.png)
![12](https://user-images.githubusercontent.com/3849885/99899277-f8dbbc00-2ccd-11eb-8a16-b201c8f6844a.png)
![13](https://user-images.githubusercontent.com/3849885/99899278-f9745280-2ccd-11eb-9a1f-df16e1da6bdb.png)

**Comment by kalyan678** [comment]
@inovizz  By tomorrow we'll be finishing all these community partner announcements which are listed here.

**Comment by inovizz** [comment]
![26](https://user-images.githubusercontent.com/3849885/100235590-a0692080-2f52-11eb-8e43-659245d390f2.png)
![27](https://user-images.githubusercontent.com/3849885/100235614-a5c66b00-2f52-11eb-9d3a-1056e1bd6fee.png)
![28](https://user-images.githubusercontent.com/3849885/100235619-a6f79800-2f52-11eb-8654-169678a2d322.png)
![29](https://user-images.githubusercontent.com/3849885/100235622-a828c500-2f52-11eb-89ba-bf085e5be53f.png)
![30](https://user-images.githubusercontent.com/3849885/100235628-a8c15b80-2f52-11eb-86fd-77ffe78700c8.png)
![31](https://user-images.githubusercontent.com/3849885/100235633-a959f200-2f52-11eb-84c4-e6cceb950130.png)

**Comment by inovizz** [comment]
@kalyan678 - rest of the posters are added as well.

**Comment by kalyan678** [comment]
@inovizz  We are good to close this task now. Thanks for your help and support 👍
