### ISSUE TITLE
Post CFP info into the following websites

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#2]
- [x] cfpland.com

- [x] confs.tech

- [x] https://github.com/nikhita/tech-conferences-india/blob/master/year-pages/2019.md

and any other similar websites which are central repos of such upcoming CFPs.

**Comment by snehithallamraju** [comment]
@inovizz Do we have specific credentials on these websites for Hydpy to post it via that id? or shall we sign up and post using our own personal ids?

**Comment by snehithallamraju** [comment]
Created an issue on tech-conference-india github page to add Pyconf Hyd to the 2020 conferences page

**Comment by inovizz** [comment]
@snehithallamraju - we can use pyconfhyderabad Gmail account to signup? I'll pass on the creds to you.

**Comment by snehithallamraju** [comment]
> @snehithallamraju - we can use pyconfhyderabad Gmail account to signup? I'll pass on the creds to you.

Sounds good.

**Comment by inovizz** [comment]
@snehithallamraju - creds shared over whatsapp.

**Comment by inovizz** [comment]
@snehithallamraju - could you please post about CFP on the first two websites, we only have 14 days left.

**Comment by snehithallamraju** [comment]
Yes will do it today in the respective websites

**Comment by inovizz** [comment]
@snehithallamraju - can you do this today?

**Comment by snehithallamraju** [comment]
Added to confs.tech

https://github.com/tech-conferences/conference-data/pulls

**Comment by snehithallamraju** [comment]
Submitted in CFP land as well

![image](https://user-images.githubusercontent.com/20667307/97599342-e30c0b80-1a2d-11eb-8014-764cd25ff9aa.png)

**Comment by inovizz** [comment]
Thanks @snehithallamraju  👍
