### ISSUE TITLE
Be like Bill campaign for Ticket Sales

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#21]
![be like bill](https://user-images.githubusercontent.com/3849885/98459988-0705e480-21c6-11eb-8f84-702308ba85a0.png)

**Comment by kalyan678** [comment]
@inovizz  When should this go?

**Comment by inovizz** [comment]
Sometime mid next week!

**Comment by kalyan678** [comment]
@inovizz  I think we can now close this task!
