### ISSUE TITLE
CFP deadline extended till 10th Nov

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#22]
- [x] Update the website
- [x] Update paper call
- [x] design the poster
- [x] Announce on Social media

**Comment by inovizz** [comment]
![cfp-extension](https://user-images.githubusercontent.com/3849885/98460482-ce1c3e80-21ca-11eb-8f2c-597d6918d583.png)

**Comment by kalyan678** [comment]
Hey @inovizz We have announced the update on on all SM channels.
