### ISSUE TITLE
Announce Third keynote speaker 13th Nov - 9:00 am

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#23]
Name - Prabhu Ramachandran 
Title - Faculty Member, Department of Aerospace Engineering, IIT Bombay
Website - https://www.aero.iitb.ac.in/~prabhu/
Description -  
```
Prabhu Ramachandran is a faculty member at the department of aerospace
engineering, IIT Bombay. His research interests include particle methods for
computational fluid dynamics, scientific computing, parallel and
high-performance computing, and applied scientific data visualization.

He has been actively involved with the FOSS and Python communities for the
past two decades. He is an active member of the SciPy community and develops
many Python-based open-source packages that are useful in the context of
scientific computing. He is the creator of the Mayavi Python package for 3D
visualization (https://github.com/enthought/mayavi). He is a PI of the FOSSEE
project (https://fossee.in) through which he has led the development of tools
and material to spread the adoption of Python. He has been a nominated fellow
of the Python Software Foundation since 2010. He was awarded the Kenneth
Gonsalves award by the Python Software Society of India and PSF in 2014. For
more information see https://www.aero.iitb.ac.in/~prabhu
```

Tasks -

- [x] Website Update
- [x] Twitter Announcement
- [x] Facebook Announcement
- [x] LinkedIn Announcement (Both on HydPy & PyConfHyd page)
- [ ] Telegram Group
- [ ] WhatsApp Group
- [ ] Zulip Chat
- [ ] Mailing List Announcement (Both meetup + HydPy mailing list)

**Comment by inovizz** [comment]
**
![image](https://user-images.githubusercontent.com/3849885/98911339-73e0ed80-24ea-11eb-8a9e-c2ec803c6345.png)
**

**Comment by kalyan678** [comment]
@bhansa I will publish the announcement on SM once the details are updated in website.

**Comment by GoelJatin** [comment]
@kalyan678 - Website is updated

**Comment by kalyan678** [comment]
@inovizz I have sent a email on mailing list(both HydPy & Meetup). Now i think we are good to close this task.
From next time I'll be careful and cross check thoroughly before we roll out the announcement on SM. 
Thank you for your continuous support!
