### ISSUE TITLE
Announce fourth Keynote - 10 am 21st November

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#24]
Name - Parul Pandey
Title - Data Scientist/ Evangelist at H2O.ai
Website - parulpandey.com
Description -  
```
Parul is currently working as a Data Scientist &  Evangelist at H2O.ai, an Automated Machine learning-based start-up based headquartered in California. Academically, she is an electrical engineer having previously worked in the field of Power Distribution at Tata Power, India. She is also the founder of a non-profit called Women in Coding & Data Science(WiCDS), whose mission is to support & promote women & gender minorities in data science, machine learning, and AI space. Parul is also a Kaggle Grandmaster in the notebooks category and was one of Linkedin’s Top Voice in the Software Development category in 2019.
```

Tasks -

- [x] Website Update
- [ ] Twitter Announcement
- [ ] Facebook Announcement
- [ ] LinkedIn Announcement (Both on HydPy & PyConfHyd page)
- [ ] Telegram Group
- [ ] WhatsApp Group
- [ ] Zulip Chat
- [ ] Mailing List Announcement (Both meetup + HydPy mailing list)

**Comment by kalyan678** [comment]
@inovizz & @bhansa  Once the website update and poster is ready, let me know so that I can schedule the announcement accordingly.

**Comment by bhansa** [comment]
let's add a picture as well and I will update it.

**Comment by inovizz** [comment]
I've added Parul as a keynote on the website. Attached is the poster.

![image](https://user-images.githubusercontent.com/3849885/99808982-b009f300-2b67-11eb-9441-664ad471016e.png)

**Comment by kalyan678** [comment]
@inovizz  We can close this task now.
