### ISSUE TITLE
Speaker Lineup announcement [3 speakers in one post]

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#26]
- [x] Sanchit to design the poster
- [ ] Kalyan to announce on Social media

**Comment by inovizz** [comment]
Recurring task 

1 post daily after community partner announcement is done.

we have a total of 19 talks so 6 posts should do.

cc @kalyan678

**Comment by inovizz** [comment]
![19](https://user-images.githubusercontent.com/3849885/100231629-516cbc80-2f4d-11eb-88f3-0198d7968981.png)
![20](https://user-images.githubusercontent.com/3849885/100231650-56ca0700-2f4d-11eb-8098-eef89229b1ac.png)
![21](https://user-images.githubusercontent.com/3849885/100231653-5893ca80-2f4d-11eb-821e-071cbe1224d5.png)
![22](https://user-images.githubusercontent.com/3849885/100231658-59c4f780-2f4d-11eb-955d-fd9b195e219f.png)
![23](https://user-images.githubusercontent.com/3849885/100231666-5b8ebb00-2f4d-11eb-8113-580c9b3cf4fe.png)

**Comment by inovizz** [comment]
We don't have images for following

1. Dominic O'Kane
2. Piyush Makhija
3. Ranjan Balappa

@poornagurram - please get us images.

**Comment by inovizz** [comment]
@kalyan678 - please post one speaker post daily, starting from tomorrow.

**Comment by inovizz** [comment]
and don't forget to tag their Twitter & LinkedIn handles.

**Comment by GoelJatin** [comment]
Let's start announcing from today.

**Comment by kalyan678** [comment]
@GoelJatin  Yes! It's already scheduled. You will see the announcements in the evening :)

**Comment by poornagurram** [comment]
Mailed the speakers. 

> We don't have images for following
> 
> 1. Dominic O'Kane
> 2. Piyush Makhija
> 3. Ranjan Balappa
> 
> @poornagurram - please get us images.

**Comment by kalyan678** [comment]
> Mailed the speakers.
> 
> > We don't have images for following
> > 
> > 1. Dominic O'Kane
> > 2. Piyush Makhija
> > 3. Ranjan Balappa
> > 
> > @poornagurram - please get us images.

@poornagurram  Did we receive any reply from speakers? If not, a reminder would be good to send!

**Comment by inovizz** [comment]
I've got the images @kalyan678 , will send you the posters for rest of them.

**Comment by kalyan678** [comment]
@inovizz  Sure Sanchit. Thanks!

**Comment by kalyan678** [comment]
@inovizz Can you please create a poster for the remaining speakers when ever you have time tomorrow so that I can announce them accordingly.

**Comment by inovizz** [comment]
![24](https://user-images.githubusercontent.com/3849885/100975732-7a500b80-3564-11eb-9923-dc789ed2a09e.png)
![25](https://user-images.githubusercontent.com/3849885/100975754-83d97380-3564-11eb-9413-8e489d31d47e.png)

**Comment by inovizz** [comment]
@kalyan678 - added the rest of the posters as well.
