### ISSUE TITLE
Conference Counter Posts to be scheduled starting from 25th November

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#27]
- [x] posters to be created by Sanchit
- [ ] Kalyan to announce on Social Media

Recurring post - daily once till 4th December.

**Comment by inovizz** [comment]
![44](https://user-images.githubusercontent.com/3849885/100201501-2458e380-2f26-11eb-8f36-4473690a451e.png)
![45](https://user-images.githubusercontent.com/3849885/100201519-2a4ec480-2f26-11eb-8f20-5cb1dd1d9e27.png)
![46](https://user-images.githubusercontent.com/3849885/100201520-2b7ff180-2f26-11eb-8090-a06da1ce0021.png)
![47](https://user-images.githubusercontent.com/3849885/100201525-2cb11e80-2f26-11eb-8380-37e777d90d2c.png)
![48](https://user-images.githubusercontent.com/3849885/100201529-2d49b500-2f26-11eb-85e0-5fcaa66b859b.png)
![49](https://user-images.githubusercontent.com/3849885/100201535-2e7ae200-2f26-11eb-812f-632920ea954c.png)
![50](https://user-images.githubusercontent.com/3849885/100201538-2f137880-2f26-11eb-8272-15a62534acb0.png)
![51](https://user-images.githubusercontent.com/3849885/100201543-2fac0f00-2f26-11eb-9fa6-1bf0f5419037.png)
![52](https://user-images.githubusercontent.com/3849885/100201549-30dd3c00-2f26-11eb-85cf-d919b64e8d7e.png)
![53](https://user-images.githubusercontent.com/3849885/100201553-320e6900-2f26-11eb-8606-d225f1dde970.png)

**Comment by kalyan678** [comment]
@inovizz  Thanks for the posters. The announcements go out as per the day!
