### ISSUE TITLE
Invite popular speakers to submit CFPs

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#4]
Few suggestions, please add more.

- [x] Sebastián Ramírez (https://github.com/tiangolo)

- [x] Ned Batchelder (https://nedbatchelder.com/site/aboutned.html)

- [x] Nikita Sobolev  (https://sobolevn.me/about/)

- [x] Dan Bader (https://dbader.org/about/)

- [x] Reuven Lerner (https://lerner.co.il/reuven-m-lerner/)

- [x] Michael Kennedy (https://blog.michaelckennedy.net/)

- [ ] Dustin Ingram (https://github.com/di)

**Comment by poornagurram** [comment]
- [ Invited ]  Sebastián Ramírez (https://github.com/tiangolo)
- [ Invited ]  Ned Batchelder (https://nedbatchelder.com/site/aboutned.html)
- [ Invited ]  Nikita Sobolev (https://sobolevn.me/about/)
- [ Invited ]  Dan Bader (https://dbader.org/about/) 
- [ Invited ]  Reuven Lerner (https://lerner.co.il/reuven-m-lerner/)
- [ Invited ]  Michael Kennedy (https://blog.michaelckennedy.net/)
- [ No email ]  Dustin Ingram (https://github.com/di)

**Comment by poornagurram** [comment]
- [x] Domonic O Kane https://github.com/domokane

**Comment by aditya-dl** [comment]
- [ ] Dipanjan Sarkar (https://github.com/dipanjanS)
