### ISSUE TITLE
Announce the first Keynote Speaker - 27th Oct 5:00 p.m.

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#5]
Name - Anand Chitipotu
Title - Software Consultant & Trainer
Website - https://anandology.com/
Description - 

```
Anand Chitipothu is a passionate programmer and long-time Pythonista. He has been crafting beautiful software for nearly two decades.

He has co-authored web.py, a micro web framework in Python, built Open Library at the Internet Archive, and created a machine learning platform at Rorodata, a startup (unsuccessful) he co-founded.

He is an elected fellow of Python Software Foundation and an active member of the Indian Python community from the early days. He has a long association with PyCon India. He was an active volunteer in the earlier years, chair for a few, spoke at many, and never missed a single one. He has initiated community projects Python Month and Python Express, which introduced the Python programming language to thousands of college students in India.

He regularly conducts public workshops and corporate trainings on niche technical topics, helping hundreds of software professionals get better at their craft.
```

Tasks -

- [x] Website Update
- [x] Twitter Announcement
- [x] Facebook Announcement
- [x] LinkedIn Announcement (Both on HydPy & PyConfHyd page)
- [x] Telegram Group
- [x] WhatsApp Group
- [x] Zulip Chat
- [x] Mailing List Announcement (Both meetup + HydPy mailing list)

**Comment by inovizz** [comment]
![anand_keynote](https://user-images.githubusercontent.com/3849885/96568051-21deea80-12e5-11eb-99bd-062d46dd8709.png)

**Comment by inovizz** [comment]
![anand_keynote](https://user-images.githubusercontent.com/3849885/97145838-db7a0780-178c-11eb-9ab4-394694f46544.png)

**Comment by inovizz** [comment]
@kalyan678 - please plan for keynote announcement tomorrow.

**Comment by inovizz** [comment]
@bhansa - could you please modify keynote speaker section in a way so that when someone clicks on it, it shows details about the speaker - Name, Title, Bio & Website.

**Comment by kalyan678** [comment]
@inovizz Btw , do we have poster ready for Keynote speaker?

**Comment by inovizz** [comment]
Its already attached in this issue.

**Comment by inovizz** [comment]
@bhansa - there is a slight change in Anand's bio, which I've updated. Kindly update the same when you modify keynote section on the website.

**Comment by kalyan678** [comment]
Hey @inovizz 

Announced the Keynote speaker on Social Media & Mailing list. I think we are good to close this task.

Thanks

**Comment by bhansa** [comment]
@inovizz @kalyan678 shall we close this?

**Comment by inovizz** [comment]
Yes, closing this.
