### ISSUE TITLE
Annnouce Second Keynote Speaker - 29th Oct 1:30 p.m.

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#8]
Name - Paul Ganssle 
Title - Senior Software Engineer @ Google
Website - https://ganssle.io/
Description -  
> Paul Ganssle is a software developer at Google, CPython core developer, maintainer of python-dateutil and setuptools and contributor to many other open source projects.  
He lives just outside of Hartford, CT where he spends his free time as traveling companion to a friendly dragon who roams the 
Connecticut River Valley in search of his lost treasure.

Tasks -

- [x] Website Update
- [x] Twitter Announcement
- [x] Facebook Announcement
- [x] LinkedIn Announcement (Both on HydPy & PyConfHyd page)
- [x] Telegram Group
- [x] WhatsApp Group
- [x] Zulip Chat
- [x] Mailing List Announcement (Both meetup + HydPy mailing list)

**Comment by GoelJatin** [comment]
Created PR https://github.com/HydPy/pyconfhyd2020/pull/21 for updating website.

@bhansa , can you please review.

@kalyan678 , need help with the SM announcements

**Comment by inovizz** [comment]
Let's have things ready and we'll announce it tomorrow morning at 9:00 am

**Comment by GoelJatin** [comment]
website changes merged, @kalyan678 , we can proceed with SM announcements

**Comment by GoelJatin** [comment]
oh okay, just read the updated title, that it's scheduled for tomorrow. NVM the previous comment

**Comment by inovizz** [comment]
![paul_keynote](https://user-images.githubusercontent.com/3849885/97540827-33fa1080-19ea-11eb-8952-f951c1c6c9a1.png)

**Comment by inovizz** [comment]
![paul_keynote](https://user-images.githubusercontent.com/3849885/97542294-83414080-19ec-11eb-9ac6-f4f38930ce56.png)

**Comment by inovizz** [comment]
Done.
