### ISSUE TITLE
Send email about CFP & Tickets being live to all previous attendees

### ISSUE THREAD

**Issue by inovizz** [HydPy/pyconfhyd2020-tasks#9]
Sanchit to get contacts of all previous attendees and Jatin to send an email.

**Comment by GoelJatin** [comment]
Hey @inovizz , did we get the list of all the previous attendees?

**Comment by inovizz** [comment]
@GoelJatin - I gave this another thought and I realized that it is not required to get the data dump. We can directly send email from townscript & explara to all previous attendees.

**Comment by inovizz** [comment]
I'll do that sometime later today.

**Comment by inovizz** [comment]
- [x] PyConf Hyd 2017
- [x] PyCon India 2018
- [x] PyConf Hyd 2019

**Comment by inovizz** [comment]
Explara didn't allow us to send more emails so I had to send the emails using Mailchimp.
